FROM golang:1.20-alpine3.17 AS builder

WORKDIR /usr/app

COPY . .

RUN go build -o captcha-lite .

FROM alpine:3.17

RUN apk update && apk add --no-cache curl ca-certificates openssl

WORKDIR /app

COPY --from=builder /usr/app/captcha-lite /app/captcha-lite

CMD [ "./captcha-lite" ]
